// terrain-generator/example/components/ColorPicker.vue
<template>
    <div class="colorpicker-container">
        <label>Color</label>
        <input
            type="color"
            :value="value"
            @input="event => onChange(event.target.value)">

        <span>{{ value }}</span>
    </div>
</template>

<script>
export default {
    props: {
        value: String,
        onChange: Function,
    },
}
</script>

// terrain-generator/example2/ColorPicker.tsx
import React from 'react';

export default function ColorPicker(props: {
    value: string;
    onChange: (value: string) => void;
}) {
    return (
    <div className="colorpicker-container">
        <label>Color</label>
        <input
            type="color"
            value={props.value}
            onChange={event => props.onChange(event.currentTarget.value)} />

        <span>{ props.value }</span>
    </div>
    )
}
