// terrain-generator/example/components/Slider.vue
<template>
    <div class="slider-container">
        <label class="slider-name">{{ name }}</label>
        <input
            type="range"
            class="slider"
            :min="min"
            :max="max"
            :step="step"
            :value="value"
            @input="onInputEvent">
        <span class="slider-value">{{ value }}</span>
    </div>
</template>

<script>
export default {
    props: {
        name: String,
        min: Number,
        max: Number,
        step: Number,
        value: Number,
        onChange: Function,
    },
    methods: {
        onInputEvent(event) {
            this.onChange(Number(event.target.value))
        }
    }
}
</script>

<style scoped>
</style>

// terrain-generator/example/Slider.tsx
import React from 'react';


export default function Slider(props: {
    name: string;
    min: number;
    max: number;
    step: number;
    value: number;
    onChange: (value: number) => void;
}) {

    return (
        <div className="slider-container">
            <label className="slider-name">{ props.name }</label>
            <input
                type="range"
                className="slider"
                min={props.min}
                max={props.max}
                step={props.step}
                value={props.value}
                onChange={e => props.onChange(Number(e.currentTarget.value))}
                />
            <span className="slider-value">{ props.value }</span>
        </div>
    )
}
