// terrain-generator/example/components/TextInput.vue
<template>
    <div class="text-input">
        <label>{{ name }}</label>
        <input
            type="text"
            :value="value"
            @input="onInputEvent">
    </div>
</template>

<script>
export default {
    props: {
        name: String,
        value: String,
        onChange: Function,
    },
    methods: {
        onInputEvent(event) {
            this.onChange(event.target.value)
        }
    }
}
</script>

// terrain-generator/example/TextInput.tsx
import React from 'react';


export default function TextInput(props: {
    name: string;
    value: string;
    onChange: (value: string) => void;
}) {

    return (
        <div className="text-input">
            <label>{ props.name }</label>
            <input
                type="text"
                value={props.value}
                onChange={e => props.onChange(e.currentTarget.value)} />
        </div>
    )
}
